name: Build
on:
  pull_request:
  push:
jobs:
  matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v1

      - name: Generate matrix
        id: set-matrix
        run: |
          set -Eeu
          echo "matrix=$(nix eval --json '.#githubActions.matrix')" >> "$GITHUB_OUTPUT"

  build:
    needs: matrix
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJSON(needs.matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v1

      - name: Install nix-build-uncached
        # Save evaluation time by pulling directly from cache.nixos.org
        # nixpkgs rev 12303c652b881435065a98729eb7278313041e49
        run: nix-env -i /nix/store/npzpwxjbxlgbi0kfji2x44nssksxk4zw-nix-build-uncached-1.1.2

      - run: nix-build-uncached .ci/get-flake.nix -A "${{ matrix.attr }}"
