name: Build
on:
  pull_request:
  push:
    branches:
      - "development"

jobs:
  matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v1

      - name: Generate matrix
        id: set-matrix
        run: |
          set -Eeu
          echo "matrix=$(nix eval --json '.#githubActions.matrix')" >> "$GITHUB_OUTPUT"

  build:
    needs: matrix
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJSON(needs.matrix.outputs.matrix)}}
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Scrounge-up some more space
        uses: samueldr/more-space-action@v2025-01-24.pre
        with:
          enable-lvm-span: true
          lvm-span-mountpoint: /nix

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v1

      - name: Override nix-daemon build directory
        run: |
          (
          PS4=" $ "
          set -eux -o pipefail

          sudo mkdir -p /nix/tmp
          sudo chmod ug=rwx,o=rwxt /nix/tmp

          sudo mkdir -p /etc/systemd/system/nix-daemon.service.d
          sudo tee /etc/systemd/system/nix-daemon.service.d/override.conf >/dev/null <<EOF
          [Service]
          Environment=TMPDIR=/nix/tmp
          EOF

          sudo systemctl daemon-reload
          sudo systemctl restart nix-daemon
          )

      - run: nix-build .ci/get-flake.nix -A "${{ matrix.attr }}"
