name: Docs
on:
  pull_request:
  push:
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - run: nix-build -A documentation

      - name: Unwrap build output
        run: |
          output=$(readlink -f result)
          cp -vr --dereference "$output" "www"

      - name: Upload archive to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 'docs'
          path: 'www'
          if-no-files-found: error
