name: Evaluate
on:
  pull_request:
  push:
jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v1

      - name: Evaluate overlay packages
        run: nix-instantiate .ci/get-flake.nix -A checks.x86_64-linux
