name: Module No-Op
on:
  pull_request:
  push:
jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v1

      - name: Verify module is a No-Op
        run: nix-instantiate ./support/nix-tests/check-no-ops.nix
